import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../../templates-data';
import image from '@/assets/templates/basic-crm.png';
import imageDark from '@/assets/templates/basic-crm-dark.png';

const now = Date.now();

export const basicCrm: Template = {
    slug: 'basic-crm',
    name: 'Basic CRM',
    shortDescription:
        'Customer Relationship Management with companies, people, and opportunities',
    description:
        'A comprehensive CRM system with companies, contacts, opportunities, and activity tracking. Perfect for small to medium businesses needing basic CRM functionality.',
    image,
    imageDark,
    tags: ['CRM', 'Business', 'MySQL', 'PostgreSQL'],
    featured: true,
    diagram: {
        id: 'basic_crm',
        name: 'basic-crm',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.MYSQL,
        tables: [
            {
                id: 'companies_table',
                name: 'companies',
                x: 100,
                y: 100,
                fields: [
                    {
                        id: 'company_id',
                        name: 'id',
                        type: { id: 'int', name: 'int' },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        increment: true,
                        createdAt: now,
                    },
                    {
                        id: 'company_name',
                        name: 'name',
                        type: { id: 'varchar', name: 'varchar' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'company_industry',
                        name: 'industry',
                        type: { id: 'varchar', name: 'varchar' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '100',
                        createdAt: now,
                    },
                    {
                        id: 'company_website',
                        name: 'website',
                        type: { id: 'varchar', name: 'varchar' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'company_phone',
                        name: 'phone',
                        type: { id: 'varchar', name: 'varchar' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '50',
                        createdAt: now,
                    },
                    {
                        id: 'company_email',
                        name: 'email',
                        type: { id: 'varchar', name: 'varchar' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'company_address',
                        name: 'address',
                        type: { id: 'text', name: 'text' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'company_city',
                        name: 'city',
                        type: { id: 'varchar', name: 'varchar' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '100',
                        createdAt: now,
                    },
                    {
                        id: 'company_state',
                        name: 'state',
                        type: { id: 'varchar', name: 'varchar' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '100',
                        createdAt: now,
                    },
                    {
                        id: 'company_country',
                        name: 'country',
                        type: { id: 'varchar', name: 'varchar' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '100',
                        createdAt: now,
                    },
                    {
                        id: 'company_postal_code',
                        name: 'postal_code',
                        type: { id: 'varchar', name: 'varchar' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '20',
                        createdAt: now,
                    },
                    {
                        id: 'company_created_at',
                        name: 'created_at',
                        type: { id: 'timestamp', name: 'timestamp' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'CURRENT_TIMESTAMP',
                        createdAt: now,
                    },
                    {
                        id: 'company_updated_at',
                        name: 'updated_at',
                        type: { id: 'timestamp', name: 'timestamp' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default:
                            'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'companies_primary',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['company_id'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'people_table',
                name: 'people',
                x: 500,
                y: 100,
                fields: [
                    {
                        id: 'person_id',
                        name: 'id',
                        type: { id: 'int', name: 'int' },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        increment: true,
                        createdAt: now,
                    },
                    {
                        id: 'person_first_name',
                        name: 'first_name',
                        type: { id: 'varchar', name: 'varchar' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '100',
                        createdAt: now,
                    },
                    {
                        id: 'person_last_name',
                        name: 'last_name',
                        type: { id: 'varchar', name: 'varchar' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '100',
                        createdAt: now,
                    },
                    {
                        id: 'person_email',
                        name: 'email',
                        type: { id: 'varchar', name: 'varchar' },
                        primaryKey: false,
                        unique: true,
                        nullable: true,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'person_phone',
                        name: 'phone',
                        type: { id: 'varchar', name: 'varchar' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '50',
                        createdAt: now,
                    },
                    {
                        id: 'person_job_title',
                        name: 'job_title',
                        type: { id: 'varchar', name: 'varchar' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '100',
                        createdAt: now,
                    },
                    {
                        id: 'person_department',
                        name: 'department',
                        type: { id: 'varchar', name: 'varchar' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '100',
                        createdAt: now,
                    },
                    {
                        id: 'person_company_id',
                        name: 'company_id',
                        type: { id: 'int', name: 'int' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'person_is_primary',
                        name: 'is_primary_contact',
                        type: { id: 'boolean', name: 'boolean' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: 'person_created_at',
                        name: 'created_at',
                        type: { id: 'timestamp', name: 'timestamp' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'CURRENT_TIMESTAMP',
                        createdAt: now,
                    },
                    {
                        id: 'person_updated_at',
                        name: 'updated_at',
                        type: { id: 'timestamp', name: 'timestamp' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default:
                            'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'people_primary',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['person_id'],
                        createdAt: now,
                    },
                    {
                        id: 'people_email_unique',
                        name: 'email',
                        unique: true,
                        fieldIds: ['person_email'],
                        createdAt: now,
                    },
                    {
                        id: 'people_company_id',
                        name: 'company_id',
                        unique: false,
                        fieldIds: ['person_company_id'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'opportunities_table',
                name: 'opportunities',
                x: 300,
                y: 400,
                fields: [
                    {
                        id: 'opportunity_id',
                        name: 'id',
                        type: { id: 'int', name: 'int' },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        increment: true,
                        createdAt: now,
                    },
                    {
                        id: 'opportunity_title',
                        name: 'title',
                        type: { id: 'varchar', name: 'varchar' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'opportunity_description',
                        name: 'description',
                        type: { id: 'text', name: 'text' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'opportunity_value',
                        name: 'value',
                        type: { id: 'decimal', name: 'decimal' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 15,
                        scale: 2,
                        createdAt: now,
                    },
                    {
                        id: 'opportunity_stage',
                        name: 'stage',
                        type: { id: 'varchar', name: 'varchar' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '50',
                        default: 'prospecting',
                        createdAt: now,
                    },
                    {
                        id: 'opportunity_probability',
                        name: 'probability',
                        type: { id: 'int', name: 'int' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'opportunity_expected_close',
                        name: 'expected_close_date',
                        type: { id: 'date', name: 'date' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'opportunity_company_id',
                        name: 'company_id',
                        type: { id: 'int', name: 'int' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'opportunity_contact_id',
                        name: 'contact_id',
                        type: { id: 'int', name: 'int' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'opportunity_created_at',
                        name: 'created_at',
                        type: { id: 'timestamp', name: 'timestamp' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'CURRENT_TIMESTAMP',
                        createdAt: now,
                    },
                    {
                        id: 'opportunity_updated_at',
                        name: 'updated_at',
                        type: { id: 'timestamp', name: 'timestamp' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default:
                            'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'opportunities_primary',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['opportunity_id'],
                        createdAt: now,
                    },
                    {
                        id: 'opportunities_company_id',
                        name: 'company_id',
                        unique: false,
                        fieldIds: ['opportunity_company_id'],
                        createdAt: now,
                    },
                    {
                        id: 'opportunities_contact_id',
                        name: 'contact_id',
                        unique: false,
                        fieldIds: ['opportunity_contact_id'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'activities_table',
                name: 'activities',
                x: 700,
                y: 400,
                fields: [
                    {
                        id: 'activity_id',
                        name: 'id',
                        type: { id: 'int', name: 'int' },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        increment: true,
                        createdAt: now,
                    },
                    {
                        id: 'activity_type',
                        name: 'type',
                        type: { id: 'varchar', name: 'varchar' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '50',
                        createdAt: now,
                    },
                    {
                        id: 'activity_subject',
                        name: 'subject',
                        type: { id: 'varchar', name: 'varchar' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'activity_description',
                        name: 'description',
                        type: { id: 'text', name: 'text' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'activity_due_date',
                        name: 'due_date',
                        type: { id: 'datetime', name: 'datetime' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'activity_completed',
                        name: 'completed',
                        type: { id: 'boolean', name: 'boolean' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: 'activity_company_id',
                        name: 'company_id',
                        type: { id: 'int', name: 'int' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'activity_person_id',
                        name: 'person_id',
                        type: { id: 'int', name: 'int' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'activity_opportunity_id',
                        name: 'opportunity_id',
                        type: { id: 'int', name: 'int' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'activity_created_at',
                        name: 'created_at',
                        type: { id: 'timestamp', name: 'timestamp' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'CURRENT_TIMESTAMP',
                        createdAt: now,
                    },
                    {
                        id: 'activity_updated_at',
                        name: 'updated_at',
                        type: { id: 'timestamp', name: 'timestamp' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default:
                            'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'activities_primary',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['activity_id'],
                        createdAt: now,
                    },
                    {
                        id: 'activities_company_id',
                        name: 'company_id',
                        unique: false,
                        fieldIds: ['activity_company_id'],
                        createdAt: now,
                    },
                    {
                        id: 'activities_person_id',
                        name: 'person_id',
                        unique: false,
                        fieldIds: ['activity_person_id'],
                        createdAt: now,
                    },
                    {
                        id: 'activities_opportunity_id',
                        name: 'opportunity_id',
                        unique: false,
                        fieldIds: ['activity_opportunity_id'],
                        createdAt: now,
                    },
                ],
                color: '#ffa726',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: 'people_company_fk',
                name: 'people_company_fk',
                sourceTableId: 'people_table',
                targetTableId: 'companies_table',
                sourceFieldId: 'person_company_id',
                targetFieldId: 'company_id',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'opportunities_company_fk',
                name: 'opportunities_company_fk',
                sourceTableId: 'opportunities_table',
                targetTableId: 'companies_table',
                sourceFieldId: 'opportunity_company_id',
                targetFieldId: 'company_id',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'opportunities_person_fk',
                name: 'opportunities_person_fk',
                sourceTableId: 'opportunities_table',
                targetTableId: 'people_table',
                sourceFieldId: 'opportunity_contact_id',
                targetFieldId: 'person_id',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'activities_company_fk',
                name: 'activities_company_fk',
                sourceTableId: 'activities_table',
                targetTableId: 'companies_table',
                sourceFieldId: 'activity_company_id',
                targetFieldId: 'company_id',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'activities_person_fk',
                name: 'activities_person_fk',
                sourceTableId: 'activities_table',
                targetTableId: 'people_table',
                sourceFieldId: 'activity_person_id',
                targetFieldId: 'person_id',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'activities_opportunity_fk',
                name: 'activities_opportunity_fk',
                sourceTableId: 'activities_table',
                targetTableId: 'opportunities_table',
                sourceFieldId: 'activity_opportunity_id',
                targetFieldId: 'opportunity_id',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
    },
};
